<?php 
$escape = $this->plugin('escapeHtml'); 
$blockClasses = $this->blockLayout()->getBlockClasses($block);
$blockStyles = $this->blockLayout()->getBlockInlineStyles($block);
?>
<div class="<?php echo $escape(implode(' ', $blockClasses)); ?>" style="<?php echo $escape(implode(' ', $blockStyles)); ?>">
    <div class="assets">
    <?php foreach ($attachments as $attachment): ?>
        <?php $asset = $attachment['asset']; ?>
        <div class="asset">
            <?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square') : ''; ?>
            <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
            <?php if ($page): ?>
                <a href="<?php echo $escape($page->siteUrl()); ?>">
                    <?php if ($assetImage !== ''): ?>
                    <div class="asset-container">
                        <?php echo $assetImage; ?>
                    </div>
                    <?php endif; ?>
                    <?php $altLinkTitle = ($attachment['alt_link_title'] !== '') ? $escape($attachment['alt_link_title']) : false; ?>
                    <span class="link-title"><?php echo ($altLinkTitle) ? $altLinkTitle : $escape($page->title()); ?></span>
                </a>
            <?php else: ?>
                <div class="asset-container">
                    <?php echo $assetImage; ?>
                </div>
            <?php endif; ?>
            <?php if ($attachment['caption'] !== ''): ?>
            <div class="caption"><?php echo $escape($attachment['caption']); ?></div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    </div>
</div>